---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_karabiner: yes
install_homebrew_if_missing: true

dotfiles_repo: https://github.com/charlesrocket/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .gitignore
  - .zshrc

homebrew_packages:
  - ansible-lint
  - autoconf
  - bash-completion
  - burp-suite
  - doxygen
  - gettext
  - git
  - go
  - fastlane
  - hashcat
  - help2man
  - httpie
  - libevent
  - makepkg
  - mc
  - micro-snitch
  - minisign
  - neofetch
  - nmap
  - node
  - nvm
  - openssl
  - php
  - ssh-copy-id
  - tor
  - wakeonlan
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_packages:
  - atom
  - chromedriver
  - docker
  - fastlane
  - firefox
  - google-chrome
  - gpg-suite-no-mail
  - karabiner-elements
  - mc
  - slack
  - vagrant

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
