---
- name: Create Karabiner folder
  file: 
    path: ~/.config/karabiner
    state: directory
    recurse: yes

- name: Copy Karabiner-Elements config file
  template:
    src: templates/karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644
    
---
- name: Create Midnight Commander folder
  file: 
    path: ~/.config/mc
    state: directory
    recurse: yes

- name: Copy Midnight Commander config file
  template:
    src: templates/mc_ini
    dest: ~/.config/mc/ini
    mode: 0644