---
- name: Create Karabiner folder
  file:
    path: /Users/{{ ansible_user_id }}/.config/karabiner
    mode: 0644
    state: directory

- name: Copy Karabiner-Elements config file
  template:
    src: templates/karabiner.json
    dest: /Users/{{ ansible_user_id }}/.config/karabiner/karabiner.json
    mode: 0644

- name: Create Midnight Commander folder
  file:
    path: /Users/{{ ansible_user_id }}/.config/mc
    mode: 0644
    state: directory

- name: Copy Midnight Commander config file
  template:
    src: templates/mc_ini
    dest: /Users/{{ ansible_user_id }}/.config/mc/ini
    mode: 0644

- name: Copy tor config file
  template:
    src: templates/torrc
    dest: /usr/local/etc/tor
    mode: 0644
