---
- name: Create dotconfig folder
  file:
    path: ~/.config
    mode: 0644
    state: directory
    owner: "{{ ansible_user_id }}"  
  
- name: Create Karabiner folder
  file:
    path: ~/.config/karabiner
    mode: 0644
    owner: "{{ ansible_user_id }}"
    state: directory

- name: Copy Karabiner-Elements config file
  template:
    src: templates/karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644

- name: Create Midnight Commander folder
  file:
    path: ~/.config/mc
    mode: 0644
    owner: "{{ ansible_user_id }}"
    state: directory

- name: Copy Midnight Commander config file
  template:
    src: templates/mc_ini
    dest: /Users/{{ ansible_user_id }}/.config/mc/ini
    mode: 0644

- name: Copy tor config file
  template:
    src: templates/torrc
    dest: /usr/local/etc/tor
    mode: 0644
