---
# General
- name: Get username
  shell: id -un
  register: username
  
- name: Copy wallpaper
  copy:
    src: files/wallpaper.jpg
    dest: "/Users/{{ username }}/Pictures/tmp_wallpaper.jpg"
    mode: 0644
    force: no
    remote_src: no

- name: Set wallpaper
  shell: sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '/Users/{{ username }}/tmp_wallpaper.jpg'"