---
# General
- name: Turn off Siri
  osx_defaults:
    domain: com.apple.assistant.support
    key: '{{ item.name }}'
    type: bool
    value: '{{ item.value }}'
  loop:
    - { name: 'Assistant Enabled', value: false }
    - { name: StatusMenuVisible, value: false }

- name: Tune interface
  osx_defaults:
    key: '{{ item.name }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - { name: AppleInterfaceStyle, type: string,  value: Dark }
    - { name: AppleHighlightColor, type: string, value: '1.000000 0.733333 0.721569 Red' }
    - { name: AccentColor, type: int, value: 0 }
    - { name: AppleAquaColorVariant, type: int, value: 1 }
  
- name: Tune Dock
  osx_defaults:
    domain: com.apple.dock
    key: '{{ item.name }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - { name: autohide, type: bool, value: false }
    - { name: show-recent, type: bool, value: false }
    - { name: magnification, type: bool, value: true }
    - { name: tilesize, type: float, value: 36 }
    - { name: largesize, type: float, value: 65 }
    - { name: mineffect, type: string, value: scale }
    
- name: Add Bong
  command: nvram StartupMute=%00
  become: yes