---
# General
- name: Switch to Dark mode
  osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: Dark
    
- name: Add bong
  command: nvram StartupMute=%00
  become: yes
  
- name: Tune Dock
  osx_defaults:
    domain: com.apple.dock
    key: '{{ item.name }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - { name: autohide, type: bool, value: false }
    - { name: tilesize, type: float, value: 36 }
    - { name: largesize, type: float, value: 65 }