---
- name: Secure keyboard entry for Terminal
  osx_defaults:
    domain: com.apple.terminal
    key: SecureKeyboardEntry
    type: bool
    value: true
    state: present

- name: Disable auto-opening of safe files for Safari
  osx_defaults:
    domain: com.apple.safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false
    state: present