---
- name: Create Karabiner folder
  file: 
    path: ~/.config/karabiner
    state: directory
    recurse: yes

- name: Copy Karabiner-Elements config file
  template:
    src: templates/karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    mode: 0644