name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    name: Linting
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: main.yml
        override-deps: ""
        args: ""