name: Ansible Playbook CI
branding:
  icon: 'book'  
  color: 'purple'

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test playbook
      run:  ci/playbook.sh
